apiVersion: v1
kind: Namespace
metadata:
  name: vault
  
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: vault
spec:
  targetNamespaces:
  - vault

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault
  namespace: vault
spec:
  channel: beta
  name: vault
  source: operatorhubio-catalog
  sourceNamespace: olm

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd

spec:
  project: default
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com/'
    targetRevision:  0.6.3
    chart: vault-operator

    helm:
      values: |

        replicaCount: 2

        etcd-operator:
          enabled: true
          etcdOperator:
            commandArgs:
              cluster-wide: true
              create-crd: false


  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

